name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liAj64XnUnYXkDEQ"
GITHUB_OWNER = "one"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://ns.995993.xyz/api/auth"
NEXT_PUBLIC_API_URL="https://ns.995993.xyz/"

